import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import { Tables, TablesInsert } from "@/integrations/supabase/types";

export type RefundClaim = Tables<"refund_claims">;

// Map database status to UI-friendly status
const mapStatusForUI = (status: RefundClaim["status"]) => {
  switch (status) {
    case "approved":
    case "paid":
      return "approved";
    case "rejected":
      return "rejected";
    case "draft":
    case "submitted":
    case "under_review":
    case "risk_assessment":
    case "officer_review":
    case "supervisor_approval":
    case "payment_processing":
    default:
      return status === "submitted" || status === "under_review" || status === "risk_assessment" 
        ? "processing" 
        : "pending";
  }
};

export const useRefundClaims = () => {
  const { user } = useAuth();

  return useQuery({
    queryKey: ["refund_claims", user?.id],
    queryFn: async () => {
      if (!user) return [];
      
      const { data, error } = await supabase
        .from("refund_claims")
        .select("*")
        .eq("taxpayer_id", user.id)
        .order("created_at", { ascending: false });

      if (error) throw error;
      return data || [];
    },
    enabled: !!user,
  });
};

export const useRefundStats = () => {
  const { data: claims = [], isLoading } = useRefundClaims();

  const stats = {
    totalClaims: claims.length,
    pendingReview: claims.filter((c) => 
      ["draft", "submitted", "under_review", "risk_assessment", "officer_review", "supervisor_approval", "payment_processing"].includes(c.status)
    ).length,
    approved: claims.filter((c) => c.status === "approved" || c.status === "paid").length,
    rejected: claims.filter((c) => c.status === "rejected").length,
    totalApprovedAmount: claims
      .filter((c) => c.status === "approved" || c.status === "paid")
      .reduce((sum, c) => sum + Number(c.claim_amount), 0),
  };

  return { stats, isLoading };
};

export const useCreateClaim = () => {
  const queryClient = useQueryClient();
  const { user } = useAuth();

  return useMutation({
    mutationFn: async (claim: { vatPeriod: string; amount: number; description?: string }) => {
      if (!user) throw new Error("User not authenticated");

      const newClaim: TablesInsert<"refund_claims"> = {
        taxpayer_id: user.id,
        claim_number: "", // Will be auto-generated by trigger
        vat_period: claim.vatPeriod,
        claim_amount: claim.amount,
        description: claim.description,
        status: "submitted",
        submitted_at: new Date().toISOString(),
      };

      const { data, error } = await supabase
        .from("refund_claims")
        .insert(newClaim)
        .select()
        .single();

      if (error) throw error;

      // Trigger auto risk assessment
      try {
        await supabase.functions.invoke("auto-risk-assessment", {
          body: { claim_id: data.id },
        });
      } catch (riskError) {
        console.error("Auto risk assessment failed:", riskError);
        // Don't block claim submission if risk assessment fails
      }

      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["refund_claims"] });
    },
  });
};

// Helper to transform database claims to UI format
export const transformClaimForUI = (claim: RefundClaim) => ({
  id: claim.id,
  claimId: claim.claim_number,
  vatPeriod: claim.vat_period,
  amount: Number(claim.claim_amount),
  submittedDate: claim.submitted_at || claim.created_at,
  status: mapStatusForUI(claim.status) as "approved" | "pending" | "rejected" | "processing",
  description: claim.description || undefined,
});
